/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    dishes: Dish;
    'catering-packages': CateringPackage;
    'quote-requests': QuoteRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    dishes: DishesSelect<false> | DishesSelect<true>;
    'catering-packages': CateringPackagesSelect<false> | CateringPackagesSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    settings: Setting;
    'home-page': HomePage;
    'menu-page': MenuPage;
    'catering-page': CateringPage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'menu-page': MenuPageSelect<false> | MenuPageSelect<true>;
    'catering-page': CateringPageSelect<false> | CateringPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  /**
   * Cloudinary Media Information
   */
  cloudinary?: {
    /**
     * Cloudinary Public ID (used for transformations)
     */
    public_id?: string | null;
    /**
     * Type of the resource (image, video, raw)
     */
    resource_type?: string | null;
    /**
     * File format
     */
    format?: string | null;
    /**
     * Secure delivery URL
     */
    secure_url?: string | null;
    /**
     * File size in bytes
     */
    bytes?: number | null;
    /**
     * Creation timestamp
     */
    created_at?: string | null;
    /**
     * Current version number
     */
    version?: string | null;
    /**
     * Unique version identifier
     */
    version_id?: string | null;
    /**
     * Width in pixels
     */
    width?: number | null;
    /**
     * Height in pixels
     */
    height?: number | null;
    /**
     * Duration in seconds (for videos)
     */
    duration?: number | null;
    /**
     * Number of pages (for PDFs)
     */
    pages?: number | null;
    /**
     * Which page of the PDF to use for thumbnails (changes will apply after saving)
     */
    selected_page?: number | null;
    /**
     * URL for the thumbnail image (automatically generated for PDFs)
     */
    thumbnail_url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dishes".
 */
export interface Dish {
  id: string;
  slug: string;
  name: string;
  /**
   * Ej: SIGNATURE · ½ LB
   */
  tag?: string | null;
  description?: string | null;
  /**
   * Ej: $17.99
   */
  price: string;
  category: 'en-vara' | 'cachapas' | 'sopa' | 'platos' | 'combos' | 'adicionales' | 'contornos' | 'postres' | 'bebidas';
  image?: (string | null) | Media;
  featured?: boolean | null;
  available?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catering-packages".
 */
export interface CateringPackage {
  id: string;
  /**
   * Identificador interno (no se traduce)
   */
  slug: string;
  name: string;
  /**
   * Ej: 10-20 GUESTS
   */
  guestRange: string;
  /**
   * Ej: from $250 o custom
   */
  price: string;
  description?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  highlighted?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Solicitudes enviadas desde el sitio. Solo lectura.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: string;
  fullName: string;
  company?: string | null;
  email: string;
  phone?: string | null;
  eventDate?: string | null;
  guestCount?: string | null;
  location?: string | null;
  package?: string | null;
  budget?: string | null;
  notes?: string | null;
  preferredContact?: ('email' | 'phone' | 'whatsapp') | null;
  source?: ('contact' | 'catering') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'dishes';
        value: string | Dish;
      } | null)
    | ({
        relationTo: 'catering-packages';
        value: string | CateringPackage;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: string | QuoteRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinary?:
    | T
    | {
        public_id?: T;
        resource_type?: T;
        format?: T;
        secure_url?: T;
        bytes?: T;
        created_at?: T;
        version?: T;
        version_id?: T;
        width?: T;
        height?: T;
        duration?: T;
        pages?: T;
        selected_page?: T;
        thumbnail_url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dishes_select".
 */
export interface DishesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  tag?: T;
  description?: T;
  price?: T;
  category?: T;
  image?: T;
  featured?: T;
  available?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catering-packages_select".
 */
export interface CateringPackagesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  guestRange?: T;
  price?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  highlighted?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  fullName?: T;
  company?: T;
  email?: T;
  phone?: T;
  eventDate?: T;
  guestCount?: T;
  location?: T;
  package?: T;
  budget?: T;
  notes?: T;
  preferredContact?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  storeName?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Se muestra en el footer y en Contacto. Cambia de idioma (EN / ES) para traducir día y horario.
   */
  hours?:
    | {
        /**
         * Ej: Monday / Lunes, o Tuesday – Thursday
         */
        day: string;
        /**
         * Ej: 11:00 AM – 9:00 PM o Closed / Cerrado
         */
        time: string;
        id?: string | null;
      }[]
    | null;
  instagram?: string | null;
  facebook?: string | null;
  tiktok?: string | null;
  whatsapp?: string | null;
  mapEmbedUrl?: string | null;
  tagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (string | null) | Media;
  /**
   * MP4 o WebM. Ideal 1920×1080 o más, 10–20s, sin pasar por WhatsApp (eso lo deja en ~480p y se ve pixelado a pantalla completa). Se reproduce una vez, se apaga al fondo oscuro y luego aparece la imagen del hero.
   */
  heroVideo?: (string | null) | Media;
  signatureTitle?: string | null;
  cateringTitle?: string | null;
  cateringDescription?: string | null;
  cateringImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-page".
 */
export interface MenuPage {
  id: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (string | null) | Media;
  /**
   * Sube un PDF distinto por idioma (EN / ES).
   */
  menuPdf?: (string | null) | Media;
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catering-page".
 */
export interface CateringPage {
  id: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (string | null) | Media;
  quoteTitle?: string | null;
  quoteDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (string | null) | Media;
  storySections?:
    | {
        /**
         * Ej: 01
         */
        number: string;
        title: string;
        body: string;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  storeName?: T;
  phone?: T;
  email?: T;
  address?: T;
  hours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  instagram?: T;
  facebook?: T;
  tiktok?: T;
  whatsapp?: T;
  mapEmbedUrl?: T;
  tagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroVideo?: T;
  signatureTitle?: T;
  cateringTitle?: T;
  cateringDescription?: T;
  cateringImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-page_select".
 */
export interface MenuPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  menuPdf?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catering-page_select".
 */
export interface CateringPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  quoteTitle?: T;
  quoteDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  storySections?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  ctaTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}